training:
  epochs: 1
  batch_size: 128
  lr: 0.001
  output_dir: /mnt/projects/debruinz_project/grant_gordon/Personal_VAE_SingleCellRNASeq/mheaded_c_vae/JobOutputs
  device: cuda

data:
  data_dir: /mnt/projects/debruinz_project/july2024_census_data/subset
  species: human
  chunks_preloaded: 1
  num_preloader_threads: 1
  vocab_builder_out: /mnt/projects/debruinz_project/grant_gordon/Personal_VAE_SingleCellRNASeq/mheaded_c_vae/preprocessed_data/

model:
  type: conditional_vae
  latent_dim: 128

metadata_vocab: /mnt/projects/debruinz_project/grant_gordon/Personal_VAE_SingleCellRNASeq/mheaded_c_vae/preprocessed_data/human_vocab_dict.pkl

metadata_fields:
  assay:
    type: onehot
  assay_ontology_term_id:
    type: IGNORE
  cell_type:
    type: embedding
    embedding_dim: 32
  cell_type_ontology_term_id:
    type: IGNORE
  dataset_id:
    type: embedding
    embedding_dim: 32
  dev_stage:
    type: onehot
  development_stage:
    type: embedding
    embedding_dim: 32
  development_stage_ontology_term_id:
    type: IGNORE
  disease:
    type: embedding
    embedding_dim: 32
  disease_ontology_term_id:
    type: IGNORE
  donor_id:
    type: IGNORE
  is_primary_data:
    type: IGNORE
  n_measured_vars:
    type: IGNORE
  nnz:
    type: IGNORE
  observation_joinid:
    type: IGNORE
  raw_mean_nnz:
    type: IGNORE
  raw_sum:
    type: IGNORE
  raw_variance_nnz:
    type: IGNORE
  self_reported_ethnicity:
    type: embedding
    embedding_dim: 32
  self_reported_ethnicity_ontology_term_id:
    type: IGNORE
  sex:
    type: onehot
  sex_ontology_term_id:
    type: IGNORE
  soma_joinid:
    type: IGNORE
  suspension_type:
    type: onehot
  tissue:
    type: embedding
    embedding_dim: 32
  tissue_general:
    type: embedding
    embedding_dim: 32
  tissue_general_ontology_term_id:
    type: IGNORE
  tissue_ontology_term_id:
    type: IGNORE
  tissue_type:
    type: IGNORE
