Global:
  seed: 0
  using_metadata: false #Flag probably wont really be used in the future, but could be useful for debug + pre conditional-layer-implementation
  scalar: float
Model:
  architecture: #Each line should be a layer, with arguements matching the corresponding Layer constructor. 
    - Linear: ["{num_features}", 512, glorot] 
    - RELU: []
    - Linear: [512, 128, florot]
    - RELU: []
    - Linear: [128, 512, glorot]
    - RELU: []
    - Linear: [ 512, "{num_features}", glorot]
  latent_dim: 128

Training:
  epochs: 1
  batch_size: 128
  lr: 0.001
  output_dir: /mnt/projects/debruinz_project/grant_gordon/Personal_VAE_SingleCellRNASeq/CVAE/JobOutputs
  
  Optimizer:
    beta1:
    beta2:
    epsilon:

Data:
  data_dir: /mnt/projects/debruinz_project/july2024_census_data/subset
  counts_file_pattern: "{species}_counts_*.npz"
  metadata_file_pattern: "{species}_metadata_*.pkl"
  vocab_builder_out: /mnt/projects/debruinz_project/grant_gordon/Personal_VAE_SingleCellRNASeq/CVAE/preprocessed_data/
  species: human
  chunks_to_preloaded: 0
  batches_to_prelaod: 0
  num_features: "" #TODO: figure out if this can be constexpr
  
ConditionalHeads:
  metadata_vocab: /mnt/projects/debruinz_project/grant_gordon/Personal_VAE_SingleCellRNASeq/CVAE/preprocessed_data/human_vocab_dict.pkl

  MetadataFields:
    Assay:
      type: onehot
    AssayOntologyTermId:
      type: IGNORE
    CellType:
      type: embedding
      embedding_dim: 128
    CellTypeOntologyTermId:
      type: IGNORE
    DatasetId:
      type: embedding
      embedding_dim: 128
    DevStage:
      type: onehot
    DevelopmentStage:
      type: embedding
      embedding_dim: 128
    DevelopmentStageOntologyTermId:
      type: IGNORE
    Disease:
      type: embedding
      embedding_dim: 128
    DiseaseOntologyTermId:
      type: IGNORE
    DonorId:
      type: embedding
      embedding_dim: 128
    IsPrimaryData:
      type: IGNORE
    NMeasuredVars:
      type: IGNORE
    Nnz:
      type: IGNORE
    ObservationJoinid:
      type: IGNORE
    RawMeanNnz:
      type: IGNORE
    RawSum:
      type: IGNORE
    RawVarianceNnz:
      type: IGNORE
    SelfReportedEthnicity:
      type: embedding
      embedding_dim: 128
    SelfReportedEthnicityOntologyTermId:
      type: IGNORE
    Sex:
      type: onehot
    SexOntologyTermId:
      type: IGNORE
    SomaJoinid:
      type: IGNORE
    SuspensionType:
      type: onehot
    Tissue:
      type: embedding
      embedding_dim: 128
    TissueGeneral:
      type: embedding
      embedding_dim: 128
    TissueGeneralOntologyTermId:
      type: IGNORE
    TissueOntologyTermId:
      type: IGNORE
    TissueType:
      type: IGNORE
