model:
  #TODO:somehow specifiy model architecture? 
  using_metadata: false
  type: FFN
  latent_dim: 128
  
training:
  epochs: 1
  batch_size: 128
  lr: 0.001
  output_dir: /mnt/projects/debruinz_project/grant_gordon/Personal_VAE_SingleCellRNASeq/CVAE/JobOutputs
  device: cuda
  lambda_l2_penalty: 0.001
  
  Optimizer:
    beta1:
    beta2:
    epsilon:

data:
  data_dir: /mnt/projects/debruinz_project/july2024_census_data/subset
  counts_file:pattern: {species}_counts_[:numeric:].npz
  metadata_file_pattern: {species}_metadata_[:numeric:].pkl
  vocab_builder_out: /mnt/projects/debruinz_project/grant_gordon/Personal_VAE_SingleCellRNASeq/CVAE/preprocessed_data/
  species: human
  chunks_to_preloaded: 0
  batches_to_prelaod: 0

conditional_heads:
  metadata_vocab: /mnt/projects/debruinz_project/grant_gordon/Personal_VAE_SingleCellRNASeq/CVAE/preprocessed_data/human_vocab_dict.pkl

  metadata_fields:
    assay:
      type: onehot
    assay_ontology_term_id:
      type: IGNORE
    cell_type:
      type: embedding
      embedding_dim: 128
    cell_type_ontology_term_id:
      type: IGNORE
    dataset_id:
      type: embedding
      embedding_dim: 128
    dev_stage:
      type: onehot
    development_stage:
      type: embedding
      embedding_dim: 128
    development_stage_ontology_term_id:
      type: IGNORE
    disease:
      type: embedding
      embedding_dim: 128
    disease_ontology_term_id:
      type: IGNORE
    donor_id:
      type: embedding
      embedding_dim: 128
    is_primary_data:
      type: IGNORE
    n_measured_vars:
      type: IGNORE
    nnz:
      type: IGNORE
    observation_joinid:
      type: IGNORE
    raw_mean_nnz:
      type: IGNORE
    raw_sum:
      type: IGNORE
    raw_variance_nnz:
      type: IGNORE
    self_reported_ethnicity:
      type: embedding
      embedding_dim: 128
    self_reported_ethnicity_ontology_term_id:
      type: IGNORE
    sex:
      type: onehot
    sex_ontology_term_id:
      type: IGNORE
    soma_joinid:
      type: IGNORE
    suspension_type:
      type: onehot
    tissue:
      type: embedding
      embedding_dim: 128
    tissue_general:
      type: embedding
      embedding_dim: 128
    tissue_general_ontology_term_id:
      type: IGNORE
    tissue_ontology_term_id:
      type: IGNORE
    tissue_type:
      type: IGNORE
