# config/discriminator_config.yaml

source_cvae:
  train_with_pretrained_cvae: false
  cvae_checkpoint_path: 
  cvae_config_path: 

# === Discriminator Architecture ===
discriminator_architecture:
  hidden_dim: 128
  dropout: 0.1
  activation: relu

# === Metadata Mutation === #TODO match with cvae config meta fields?
fields_to_change:
  - cell_type
  - sex

training:
  device: cuda
  learning_rate: 0.001
  freeze_cvae: false
  train_last_n_epochs: 2

