#include <glob.h>
#include "config.h"

//AI Acknowledgement - This method was fully generated by chatGPT
//TODO: no clue how this function works, operating on blind faith atm
std::vector<std::string> get_matching_files(const std::vector<std::string>& path, const std::string& pattern){
    std::string full_pattern = path + pattern;

    glob_t glob_result;
    glob(full_pattern.c_str(), GLOB_TILDE, nullptr, &glob_result);
    std::vector<std::string> files;
    for (int i = 0; i< glob_result.gl_pathc; ++i){
        files.emplace_back(glob_result.gl_pathv[i]);
    }
    globfree(&glob_result);
    return files;
}