//AI- acknowledgement: this file was generated by chatGPT
//dummy_values.h
#pragma once
#include "custom_types.h"

// Dense input: batch_size=4, input_dim=5
template <typename Scalar>
inline MatrixD<Scalar> get_dummy_input_matrix() {
    MatrixD<Scalar> mat(4, 5);
    mat << 1.0,  0.0, -1.0, 2.0,  0.5,
           0.5,  2.0,  0.3, 0.0, -0.7,
          -1.5,  1.2,  0.0, 0.8,  1.1,
           0.0, -0.4,  0.9, 1.3, -1.0;
    return mat;
}

// Upstream gradient: batch_size=4, output_dim=6
template <typename Scalar>
inline MatrixD<Scalar> get_dummy_upstream_grad(int output_dim = 6) {
    MatrixD<Scalar> grad(4, output_dim);
    grad << 0.1, 0.2, 0.3, 0.4, 0.5, 0.6,
            0.2, 0.1, 0.4, 0.3, 0.6, 0.5,
            0.3, 0.4, 0.1, 0.2, 0.5, 0.6,
            0.4, 0.3, 0.2, 0.1, 0.6, 0.5;
    return grad;
}

// Sparse input: batch_size=4, input_dim=5
template <typename Scalar>
inline Batch<Scalar> get_dummy_sparse_batch() {
    Batch<Scalar> batch(4);

    batch[0]->indices = {0, 2, 4}; batch[0]->data = {1.0, -1.0, 0.5}; batch[0]->nnz = 3;
    batch[1]->indices = {1, 3};    batch[1]->data = {0.5, 2.0};      batch[1]->nnz = 2;
    batch[2]->indices = {0, 1, 4}; batch[2]->data = {-1.5, 1.2, 1.1};batch[2]->nnz = 3;
    batch[3]->indices = {2, 3};    batch[3]->data = {0.9, 1.3};      batch[3]->nnz = 2;

    return batch;
}

// Deterministic initializer
template <typename Scalar>
inline InitFn<Scalar> get_dummy_init_fn() {
    return [](int in_dim, int out_dim, std::mt19937&) {
        return 0.05 * (in_dim + out_dim); // Deterministic but varied
    };
}
